import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { Fraunces } from "next/font/google";
import { Playfair_Display } from "next/font/google";


const playfairDisplay = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
  style: ['normal', 'italic'],
  weight: ['400', '500', '600', '700'],
});

const denton = localFont ({
  src:[
    {
      path:"../public/fonts/Denton-Test-Bold-700.ttf"
    },
  ],
  variable:"--font-denton",
})


const fraunces = Fraunces({
  variable: "--font-fraunces",
  subsets: ["latin"],
  style: ['normal', 'italic'],
  weight: ['400', '500', '600', '700', '900'],
});



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Superlevelfinal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${denton.variable} ${fraunces.variable} ${playfairDisplay.variable}  ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
